//
//  NumbersListWorker.swift
//  RandomNubmbers
//
//  Created by Kovtun on 4/12/18.
//  Copyright (c) 2018 Kovtun. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NumbersListWorker {

    private struct Constants {
        static let maxNumbersCount = 10
        static let upRandom: UInt32 = 100
    }
    
    func randomizeNumbers(completion: (([Number]) -> Void)) {
        var numbers = [Number](repeating: Number(value: 0), count: Constants.maxNumbersCount)
        
        for i in 0..<numbers.count {
            numbers[i] = addRandomNumber()
        }
        completion(numbers)
    }

    func addRandomNumber() -> Number {
        return Number(value: Int(arc4random_uniform(Constants.upRandom)))
    }
}
