//
//  NumbersListPresenter.swift
//  RandomNubmbers
//
//  Created by Kovtun on 4/12/18.
//  Copyright (c) 2018 Kovtun. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NumbersListPresentationLogic {
    func presentNumbers(response: NumbersList.GeneratedNumbers.Response)
}

class NumbersListPresenter: NumbersListPresentationLogic {
    weak var viewController: NumbersListDisplayLogic?
    
    // MARK: presentNumbers
    
    func presentNumbers(response: NumbersList.GeneratedNumbers.Response) {
        var displayedNumbers = [NumbersList.GeneratedNumbers.ViewModel.DisplayedNumber]()
        for number in response.numbers {
            displayedNumbers.append(NumbersList.GeneratedNumbers.ViewModel.DisplayedNumber(number: number.value))
        }
        let viewModel = NumbersList.GeneratedNumbers.ViewModel(displayedNumbers: displayedNumbers)
        viewController?.displayNumbers(viewModel: viewModel)
    }
}
