//
//  NumbersListModels.swift
//  RandomNubmbers
//
//  Created by Kovtun on 4/12/18.
//  Copyright (c) 2018 Kovtun. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NumbersList {
    // MARK: Use cases
    
    enum GeneratedNumbers {
        struct Request {
            let indexDeletingNumber: Int
        }
        
        struct Response {
            var numbers: [Number]
        }
        
        struct ViewModel {
            struct DisplayedNumber {
                var number: Int
            }
            
            var displayedNumbers: [DisplayedNumber]
        }
    }
}
